/* YEARS */
export const GET_YEARS = "GET_YEARS"
export const GET_YEARS_SUCCESS = "GET_YEARS_SUCCESS"
export const GET_YEARS_FAIL = "GET_YEARS_FAIL"

export const ADD_YEAR = "ADD_YEAR"
export const ADD_YEAR_SUCCESS = "ADD_YEAR_SUCCESS"
export const ADD_YEAR_FAIL = "ADD_YEAR_FAIL"

export const UPDATE_YEAR = "UPDATE_YEAR"
export const UPDATE_YEAR_SUCCESS = "UPDATE_YEAR_SUCCESS"
export const UPDATE_YEAR_FAIL = "UPDATE_YEAR_FAIL"

export const DELETE_YEAR = "DELETE_YEAR"
export const DELETE_YEAR_SUCCESS = "DELETE_YEAR_SUCCESS"
export const DELETE_YEAR_FAIL = "DELETE_YEAR_FAIL"
