/* KEYSTAGES */
export const GET_VIDEO_ITEM = "GET_VIDEO_ITEM"
export const GET_VIDEO_ITEM_SUCCESS = "GET_VIDEO_ITEM_SUCCESS"
export const GET_VIDEO_ITEM_FAIL = "GET_VIDEO_ITEM_FAIL"

export const GET_VIDEOS = "GET_VIDEOS"
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS"
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL"

export const ADD_VIDEOS = "ADD_VIDEOS"
export const ADD_VIDEOS_SUCCESS = "ADD_VIDEOS_SUCCESS"
export const ADD_VIDEOS_FAIL = "ADD_VIDEOS_FAIL"

export const UPDATE_VIDEOS = "UPDATE_VIDEOS"
export const UPDATE_VIDEOS_SUCCESS = "UPDATE_VIDEOS_SUCCESS"
export const UPDATE_VIDEOS_FAIL = "UPDATE_VIDEOS_FAIL"

export const DELETE_VIDEOS = "DELETE_VIDEOS"
export const DELETE_VIDEOS_SUCCESS = "DELETE_VIDEOS_SUCCESS"
export const DELETE_VIDEOS_FAIL = "DELETE_VIDEOS_FAIL"

export const VERIFY_NEW_VIDEOS = "VERIFY_NEW_VIDEOS"
export const VERIFY_NEW_VIDEOS_SUCCESS = "VERIFY_NEW_VIDEOS_SUCCESS"
export const VERIFY_NEW_VIDEOS_FAIL = "VERIFY_NEW_VIDEOS_FAIL"