/* Subjects */
export const GET_SUBJECTS = "GET_SUBJECTS"
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS"
export const GET_SUBJECTS_FAIL = "GET_SUBJECTS_FAIL"

export const ADD_SUBJECT = "ADD_SUBJECT"
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS"
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL"

export const UPDATE_SUBJECT = "UPDATE_SUBJECT"
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS"
export const UPDATE_SUBJECT_FAIL = "UPDATE_SUBJECT_FAIL"

export const DELETE_SUBJECT = "DELETE_SUBJECT"
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS"
export const DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL"