/* KEYSTAGES */
export const GET_PASTPAPER_ITEM = "GET_PASTPAPER_ITEM"
export const GET_PASTPAPER_ITEM_SUCCESS = "GET_PASTPAPER_ITEM_SUCCESS"
export const GET_PASTPAPER_ITEM_FAIL = "GET_PASTPAPER_ITEM_FAIL"

export const GET_PASTPAPER = "GET_PASTPAPER"
export const GET_PASTPAPER_SUCCESS = "GET_PASTPAPER_SUCCESS"
export const GET_PASTPAPER_FAIL = "GET_PASTPAPER_FAIL"

export const ADD_PASTPAPER = "ADD_PASTPAPER"
export const ADD_PASTPAPER_SUCCESS = "ADD_PASTPAPER_SUCCESS"
export const ADD_PASTPAPER_FAIL = "ADD_PASTPAPER_FAIL"

export const UPDATE_PASTPAPER = "UPDATE_PASTPAPER"
export const UPDATE_PASTPAPER_SUCCESS = "UPDATE_PASTPAPER_SUCCESS"
export const UPDATE_PASTPAPER_FAIL = "UPDATE_PASTPAPER_FAIL"

export const DELETE_PASTPAPER = "DELETE_PASTPAPER"
export const DELETE_PASTPAPER_SUCCESS = "DELETE_PASTPAPER_SUCCESS"
export const DELETE_PASTPAPER_FAIL = "DELETE_PASTPAPER_FAIL"