/* SELF TEST */
export const GET_SELF_TEST = "GET_SELFTEST_ITEM"
export const GET_SELF_TEST_SUCCESS = "GET_SELFTEST_ITEM_SUCCESS"
export const GET_SELF_TEST_FAIL = "GET_SELFTEST_ITEM_FAIL"

export const GET_SELF_TESTS = "GET_SELFTEST"
export const GET_SELF_TESTS_SUCCESS = "GET_SELFTEST_SUCCESS"
export const GET_SELF_TESTS_FAIL = "GET_SELFTEST_FAIL"

export const ADD_SELF_TEST = "ADD_SELFTEST"
export const ADD_SELF_TEST_SUCCESS = "ADD_SELFTEST_SUCCESS"
export const ADD_SELF_TEST_FAIL = "ADD_SELFTEST_FAIL"

export const UPDATE_SELF_TEST = "UPDATE_SELFTEST"
export const UPDATE_SELF_TEST_SUCCESS = "UPDATE_SELFTEST_SUCCESS"
export const UPDATE_SELF_TEST_FAIL = "UPDATE_SELFTEST_FAIL"

export const DELETE_SELF_TEST = "DELETE_SELFTEST"
export const DELETE_SELF_TEST_SUCCESS = "DELETE_SELFTEST_SUCCESS"
export const DELETE_SELF_TEST_FAIL = "DELETE_SELFTEST_FAIL"
