/* KEYSTAGES */
export const GET_CHAPTERS = "GET_CHAPTERS"
export const GET_CHAPTERS_SUCCESS = "GET_CHAPTERS_SUCCESS"
export const GET_CHAPTERS_FAIL = "GET_CHAPTERS_FAIL"

export const FILTER_CHAPTER = "FILTER_CHAPTER"
export const FILTER_CHAPTER_SUCCESS = "FILTER_CHAPTER_SUCCESS"
export const FILTER_CHAPTER_FAIL = "FILTER_CHAPTER_FAIL"

export const ADD_CHAPTER = "ADD_CHAPTER"
export const ADD_CHAPTER_SUCCESS = "ADD_CHAPTER_SUCCESS"
export const ADD_CHAPTER_FAIL = "ADD_CHAPTER_FAIL"

export const UPDATE_CHAPTER = "UPDATE_CHAPTER"
export const UPDATE_CHAPTER_SUCCESS = "UPDATE_CHAPTER_SUCCESS"
export const UPDATE_CHAPTER_FAIL = "UPDATE_CHAPTER_FAIL"

export const DELETE_CHAPTER = "DELETE_CHAPTER"
export const DELETE_CHAPTER_SUCCESS = "DELETE_CHAPTER_SUCCESS"
export const DELETE_CHAPTER_FAIL = "DELETE_CHAPTER_FAIL"