/* EXAM BOARDS */
export const GET_EXAM_BOARDS = "GET_EXAM_BOARDS"
export const GET_EXAM_BOARDS_SUCCESS = "GET_EXAM_BOARDS_SUCCESS"
export const GET_EXAM_BOARDS_FAIL = "GET_EXAM_BOARDS_FAIL"

/* USERS PROFILE */
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL"

export const ADD_NEW_EXAM_BOARD = "ADD_NEW_EXAM_BOARD"
export const ADD_EXAM_BOARD_SUCCESS = "ADD_EXAM_BOARD_SUCCESS"
export const ADD_EXAM_BOARD_FAIL = "ADD_EXAM_BOARD_FAIL"

export const UPDATE_EXAM_BOARD = "UPDATE_EXAM_BOARD"
export const UPDATE_EXAM_BOARD_SUCCESS = "UPDATE_EXAM_BOARD_SUCCESS"
export const UPDATE_EXAM_BOARD_FAIL = "UPDATE_EXAM_BOARD_FAIL"

export const DELETE_EXAM_BOARD = "DELETE_EXAM_BOARD"
export const DELETE_EXAM_BOARD_SUCCESS = "DELETE_EXAM_BOARD_SUCCESS"
export const DELETE_EXAM_BOARD_FAIL = "DELETE_EXAM_BOARD_FAIL"
