/* KEYSTAGES */
export const GET_WORKSHEET_QUESTIONS = "GET_WORKSHEET_QUESTIONS"
export const GET_WORKSHEET_QUESTIONS_SUCCESS = "GET_WORKSHEET_QUESTIONS_SUCCESS"
export const GET_WORKSHEET_QUESTIONS_FAIL = "GET_WORKSHEET_QUESTIONS_FAIL"

export const ADD_WORKSHEET_QUESTIONS = "ADD_WORKSHEET_QUESTIONS"
export const ADD_WORKSHEET_QUESTIONS_SUCCESS = "ADD_WORKSHEET_QUESTIONS_SUCCESS"
export const ADD_WORKSHEET_QUESTIONS_FAIL = "ADD_WORKSHEET_QUESTIONS_FAIL"

export const UPDATE_WORKSHEET_QUESTIONS = "UPDATE_WORKSHEET_QUESTIONS"
export const UPDATE_WORKSHEET_QUESTIONS_SUCCESS = "UPDATE_WORKSHEET_QUESTIONS_SUCCESS"
export const UPDATE_WORKSHEET_QUESTIONS_FAIL = "UPDATE_WORKSHEET_QUESTIONS_FAIL"

export const DELETE_WORKSHEET_QUESTIONS = "DELETE_WORKSHEET_QUESTIONS"
export const DELETE_WORKSHEET_QUESTIONS_SUCCESS = "DELETE_WORKSHEET_QUESTIONS_SUCCESS"
export const DELETE_WORKSHEET_QUESTIONS_FAIL = "DELETE_WORKSHEET_QUESTIONS_FAIL"