/* KEYSTAGES */
export const GET_LESSONS = "GET_LESSONS"
export const GET_LESSONS_SUCCESS = "GET_LESSONS_SUCCESS"
export const GET_LESSONS_FAIL = "GET_LESSONS_FAIL"

export const ADD_LESSON = "ADD_LESSON"
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS"
export const ADD_LESSON_FAIL = "ADD_LESSON_FAIL"

export const UPDATE_LESSON = "UPDATE_LESSON"
export const UPDATE_LESSON_SUCCESS = "UPDATE_LESSON_SUCCESS"
export const UPDATE_LESSON_FAIL = "UPDATE_LESSON_FAIL"

export const DELETE_LESSON = "DELETE_LESSON"
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS"
export const DELETE_LESSON_FAIL = "DELETE_LESSON_FAIL"

export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN"
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS"
export const GET_ACCESS_TOKEN_FAIL = "GET_ACCESS_TOKEN_FAIL"

export const CREATE_VIDEO = "CREATE_VIDEO"
export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS"
export const CREATE_VIDEO_FAIL = "CREATE_VIDEO_FAIL"

export const VERIFY_VIDEO = "VERIFY_VIDEO"
export const VERIFY_VIDEO_SUCCESS = "VERIFY_VIDEO_SUCCESS"
export const VERIFY_VIDEO_FAIL = "VERIFY_VIDEO_FAIL"