/* SELF TEST QUESTIONS */
export const GET_SELFTEST_QUESTIONS = "GET_SELFTEST_QUESTIONS"
export const GET_SELFTEST_QUESTIONS_SUCCESS = "GET_SELFTEST_QUESTIONS_SUCCESS"
export const GET_SELFTEST_QUESTIONS_FAIL = "GET_SELFTEST_QUESTIONS_FAIL"

export const ADD_SELFTEST_QUESTIONS = "ADD_SELFTEST_QUESTIONS"
export const ADD_SELFTEST_QUESTIONS_SUCCESS = "ADD_SELFTEST_QUESTIONS_SUCCESS"
export const ADD_SELFTEST_QUESTIONS_FAIL = "ADD_SELFTEST_QUESTIONS_FAIL"

export const UPDATE_SELFTEST_QUESTIONS = "UPDATE_SELFTEST_QUESTIONS"
export const UPDATE_SELFTEST_QUESTIONS_SUCCESS = "UPDATE_SELFTEST_QUESTIONS_SUCCESS"
export const UPDATE_SELFTEST_QUESTIONS_FAIL = "UPDATE_SELFTEST_QUESTIONS_FAIL"

export const DELETE_SELFTEST_QUESTIONS = "DELETE_SELFTEST_QUESTIONS"
export const DELETE_SELFTEST_QUESTIONS_SUCCESS = "DELETE_SELFTEST_QUESTIONS_SUCCESS"
export const DELETE_SELFTEST_QUESTIONS_FAIL = "DELETE_SELFTEST_QUESTIONS_FAIL"
