/* KEYSTAGES */
export const GET_PASTPAPER_QUESTIONS = "GET_PASTPAPER_QUESTIONS"
export const GET_PASTPAPER_QUESTIONS_SUCCESS = "GET_PASTPAPER_QUESTIONS_SUCCESS"
export const GET_PASTPAPER_QUESTIONS_FAIL = "GET_PASTPAPER_QUESTIONS_FAIL"

export const ADD_PASTPAPER_QUESTIONS = "ADD_PASTPAPER_QUESTIONS"
export const ADD_PASTPAPER_QUESTIONS_SUCCESS = "ADD_PASTPAPER_QUESTIONS_SUCCESS"
export const ADD_PASTPAPER_QUESTIONS_FAIL = "ADD_PASTPAPER_QUESTIONS_FAIL"

export const UPDATE_PASTPAPER_QUESTIONS = "UPDATE_PASTPAPER_QUESTIONS"
export const UPDATE_PASTPAPER_QUESTIONS_SUCCESS = "UPDATE_PASTPAPER_QUESTIONS_SUCCESS"
export const UPDATE_PASTPAPER_QUESTIONS_FAIL = "UPDATE_PASTPAPER_QUESTIONS_FAIL"

export const DELETE_PASTPAPER_QUESTIONS = "DELETE_PASTPAPER_QUESTIONS"
export const DELETE_PASTPAPER_QUESTIONS_SUCCESS = "DELETE_PASTPAPER_QUESTIONS_SUCCESS"
export const DELETE_PASTPAPER_QUESTIONS_FAIL = "DELETE_PASTPAPER_QUESTIONS_FAIL"