/* KEYSTAGES */
export const GET_WORKSHEET_ITEM = "GET_WORKSHEET_ITEM"
export const GET_WORKSHEET_ITEM_SUCCESS = "GET_WORKSHEET_ITEM_SUCCESS"
export const GET_WORKSHEET_ITEM_FAIL = "GET_WORKSHEET_ITEM_FAIL"

export const GET_WORKSHEET = "GET_WORKSHEET"
export const GET_WORKSHEET_SUCCESS = "GET_WORKSHEET_SUCCESS"
export const GET_WORKSHEET_FAIL = "GET_WORKSHEET_FAIL"

export const ADD_WORKSHEET = "ADD_WORKSHEET"
export const ADD_WORKSHEET_SUCCESS = "ADD_WORKSHEET_SUCCESS"
export const ADD_WORKSHEET_FAIL = "ADD_WORKSHEET_FAIL"

export const UPDATE_WORKSHEET = "UPDATE_WORKSHEET"
export const UPDATE_WORKSHEET_SUCCESS = "UPDATE_WORKSHEET_SUCCESS"
export const UPDATE_WORKSHEET_FAIL = "UPDATE_WORKSHEET_FAIL"

export const DELETE_WORKSHEET = "DELETE_WORKSHEET"
export const DELETE_WORKSHEET_SUCCESS = "DELETE_WORKSHEET_SUCCESS"
export const DELETE_WORKSHEET_FAIL = "DELETE_WORKSHEET_FAIL"