/* KEY STAGES */
export const GET_KEY_STAGES = "GET_KEY_STAGES"
export const GET_KEY_STAGES_SUCCESS = "GET_KEY_STAGES_SUCCESS"
export const GET_KEY_STAGES_FAIL = "GET_KEY_STAGES_FAIL"

export const ADD_KEY_STAGE = "ADD_KEY_STAGE"
export const ADD_KEY_STAGE_SUCCESS = "ADD_KEY_STAGE_SUCCESS"
export const ADD_KEY_STAGE_FAIL = "ADD_KEY_STAGE_FAIL"

export const UPDATE_KEY_STAGE = "UPDATE_KEY_STAGE"
export const UPDATE_KEY_STAGE_SUCCESS = "UPDATE_KEY_STAGE_SUCCESS"
export const UPDATE_KEY_STAGE_FAIL = "UPDATE_KEY_STAGE_FAIL"

export const DELETE_KEY_STAGE = "DELETE_KEY_STAGE"
export const DELETE_KEY_STAGE_SUCCESS = "DELETE_KEY_STAGE_SUCCESS"
export const DELETE_KEY_STAGE_FAIL = "DELETE_KEY_STAGE_FAIL"
